print("Donner nombre pour A")
A = int(input())
print("Donner nombre pour B")
B = int(input())
print("No 1 de l'exercise")
print(A, B, sep="\n")
print("No 2 de l'exercise")
print(A, ",", B)
print("No 3 de l'exercise")
print("A=", A, "et B=", B, sep=" ")
print("No 4 de l'exercise")
print(A,B,A,"\n",B,A,B,"\n",A,B,A,sep=" ")
print("No 5 de l'exercise")
print(A,B,A,B, end="!", sep="-")